#################
# Keycloak DB
#################
---
apiVersion: v1
data:
  keycloak-db-username: a2V5Y2xvYWsK
  keycloak-db-password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    label: aaa
  name: keycloak-secrets
  namespace: aaa
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  labels:
    app: keycloak-db-service
  namespace: aaa
spec:
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  selector:
    app: keycloak-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
  namespace: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: keycloak-db
          image: harbor.teresol.com/aaa/keycloak-postgres:1.0.0
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-db-data-volume
              subPath: postgres
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: keycloak-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: keycloak-db-password
          ports:
            - name: http
              containerPort: 5432
      volumes:
        - name: keycloak-db-data-volume
          persistentVolumeClaim:
            claimName: keycloak-db-data-volume-claim
