---
apiVersion: v1
kind: Service
metadata:
  namespace: esm
  labels:
    app: dataaccessmstieupreporting
  name: dataaccessmstieupreporting
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8088
      nodePort: 31411
  selector:
    app: dataaccessmstieupreporting
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: esm
  labels:
    app: dataaccessmstieupreporting
  name: dataaccessmstieupreporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmstieupreporting
  template:
    metadata:
      labels:
        app: dataaccessmstieupreporting
    spec:
      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER

      containers:
        - env:
            - name: DATAACCESS_TIEUP_REPORTING_PORT
              value: "8088"
            - name: DATAACCESS_TIEUP_REPORTING_HOST
              value: "0.0.0.0"
            - name: DATAACCESS_TIEUP_REPORTING_CORS
              value: "true"
            - name: DB-KIND
              value: "mssql" 
            - name: DB_USER
              value: "JVb7gFmW3KDBw5oyWPhUbg=="
            - name: DB_PASS
              value: "8eK0duD7z1u/F1GCisSqVQ=="
            - name: SQL_USERNAME
              value: "rps" 
            - name: SQL_PASSWORD
              value: "Rps123/?" 
            - name: SQL_SERVER_IP
              value: "10.90.95.85" 
            - name: SQL_SERVER_PORT
              value: "1433" 
            - name: DATABASE_NAME
              value: "HR_DirectPayment"
            - name: SQL_DRIVER
              value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"    
                                                                                                 
          image: harbor.teresol.com/coreservices/dataaccessmstieupreporting:1.2.6
          imagePullPolicy: Always
          name: dataaccessmstieupreporting
          ports:
            - containerPort: 8088
              name: http
              protocol: TCP
