apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-08-29T14:20:28Z"
  labels:
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "39"
  uid: e9c803d9-ff5f-49c9-a68d-6763e77d6a27
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
