###############################
# AAA user-detail-data-access
###############################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: aaa-user-detail-data-access-service-crm
  name: aaa-user-detail-data-access-service-crm
  namespace: aaa
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      #      nodePort: 30381
  selector:
    app: aaa-user-detail-data-access-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa-user-detail-data-access-crm
  labels:
    app: aaa-user-detail-data-access-crm
  namespace: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa-user-detail-data-access-crm
  template:
    metadata:
      labels:
        app: aaa-user-detail-data-access-crm
    spec:
      #nodeSelector:
        #kubernetes.io/role: CORE-WORKER
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: DATAACCESS_MS_VALIDATE_BRANCH
              value: "http://dataaccessmsvalidatebranch-crm.teresol.svc.cluster.local:80"

          name: aaa-user-detail-data-access-crm
          image: harbor.teresol.com/aaa/aaa-user-detail-data-access:2.0.6-crm
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
