#####################################
# AAA aaa-user-list-data-access
#####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa-user-list-data-access-crm
  labels:
    app: aaa-user-list-data-access-crm
  namespace: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa-user-list-data-access-crm
  template:
    metadata:
      labels:
        app: aaa-user-list-data-access-crm
    spec:
      #nodeSelector:
        #kubernetes.io/role: CORE-WORKER

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap

          name: aaa-user-list-data-access-crm
          image: harbor.teresol.com/aaa/aaa-user-list-data-access:1.3.0-crm
          resources: {}
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: aaa-user-list-data-access-service-crm
  name: aaa-user-list-data-access-service-crm
  namespace: aaa
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      #      nodePort: 31897
  selector:
    app: aaa-user-list-data-access-crm
  type: NodePort

