---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: obs-uc13-2-lca-oa-c
  name: obs-uc13-2-lca-oa-c
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-uc13-2-lca-oa-c
  template:
    metadata:
      labels:
        app: obs-uc13-2-lca-oa-c
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/obs-uc13-2-lca-oa-c:1.2.2
          imagePullPolicy: Always
          name: obs-uc13-2-lca-oa-c
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: obs-uc13-2-lca-oa-c
  name: obs-uc13-2-lca-oa-c
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: obs-uc13-2-lca-oa-c
  type: ClusterIP

#################################


#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-obs-uc13-2-lca-oa-c
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/OBS_UC13_2_LCA_OA_C`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: obs-uc13-2-lca-oa-c
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret
