---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirt-crm
  name: coremsreportbirt-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsreportbirt-crm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coremsreportbirt-crm
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
            #      nodeName: r2bcbs.dev.server12       #r2bcbs.dev.server28
#      #nodeSelector:
#        #kubernetes.io/role: CORE-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_IP
              value: "redisserver.teresol.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"

          image: harbor.teresol.com/reporting/coremsreportbirt:0.0.1-crm
          name: coremsreportbirt-crm
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /birt/reports
              name: coremsreportbirt-data
          securityContext:
             capabilities:
                add: ["SYS_ADMIN"]

      restartPolicy: Always
      volumes:
        - name: coremsreportbirt-data
          hostPath:
             path: /BirtReports
             type: DirectoryOrCreate
          #          persistentVolumeClaim:
          #            claimName: coremsreportbirt-crm-data-claim

#########################################################################
---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirt-crm
  name: coremsreportbirt-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30994
  selector:
    app: coremsreportbirt-crm
  type: NodePort
