---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirtquarkus-crm
  name: coremsreportbirtquarkus-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsreportbirtquarkus-crm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coremsreportbirtquarkus-crm
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeName: r2bcbsint29.bank.alhabib.com            #r2bcbsint23.bank.alhabib.com

#      #nodeSelector:
#        #kubernetes.io/role: CORE-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_IP
              value: "redisserver.teresol.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"

            - name: MSSQLRTPS_DATABASE_IP
              value: "10.90.93.12"
            - name: MSSQLRTPS_DATABASE_PORT
              value: "1433"

            - name: DATABASE_NANE
              value: "HR_DirectPayment"

            - name: MSSQLRTPS_USERNAME
              value: "U3/uuaZHqiAWJWm3DCf+qg=="

            - name: MSSQLRTPS_PASSWORD
              value: "CY+jVqhEuJ24nNngtOYYug=="

          image: harbor.teresol.com/reporting/coremsreportbirtquarkus:0.0.4-crm
          name: coremsreportbirtquarkus-crm
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /deployments/reports
              name: coremsreportbirtquarkus-data
          securityContext:
             capabilities:
                add: ["SYS_ADMIN"]

          resources:
           requests:
             memory: "1000Mi"
             #  cpu: "200m"
           limits:
              memory: "4000Mi"
              #  cpu: "2000m"

      restartPolicy: Always
      volumes:
        - name: coremsreportbirtquarkus-data
          hostPath:
             path: /BirtReports
             type: DirectoryOrCreate
          #          persistentVolumeClaim:
          #            claimName: coremsreportbirtquarkus-data-claim

#########################################################################
---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirtquarkus-crm
  name: coremsreportbirtquarkus-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31575
  selector:
    app: coremsreportbirtquarkus-crm
  type: NodePort
