---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coremsreport
  name: coremsreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsreport
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coremsreport
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      securityContext:
        fsGroup: 1001

      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: JASPERREPORTS_DATABASE_HOST
              value: "coremsreport-db"
            - name: JASPERREPORTS_DATABASE_NAME
              value: bitnami_jasperreports
            - name: JASPERREPORTS_DATABASE_PORT_NUMBER
              value: "3306"
            - name: JASPERREPORTS_DATABASE_USER
              value: bn_jasperreports
            - name: JASPERREPORTS_EMAIL
              value: devops.isb@teresol.com
            - name: JASPERREPORTS_PASSWORD
              value: admin@123
            - name: JASPERREPORTS_USERNAME
              value: admin
          image: harbor.teresol.com/teresol/coremsreport:1.1.1
          name: coremsreport
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/jasperreports
              name: coremsreport-data
            - mountPath: /bitnami/jasperreports-mounted-conf
              name: coremsreport-conf
      restartPolicy: Always
      volumes:
        - name: coremsreport-data
          persistentVolumeClaim:
            claimName: coremsreport-data-claim
        - name: coremsreport-conf
          persistentVolumeClaim:
            claimName: coremsreport-conf-claim

##############################################
---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coremsreport
  name: coremsreport
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: coremsreport
  type: NodePort
