---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirtquarkus
  name: coremsreportbirtquarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsreportbirtquarkus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coremsreportbirtquarkus
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeName: r2bcbsint29.bank.alhabib.com            #r2bcbsint23.bank.alhabib.com
#      #knodeSelector:
#        #kubernetes.io/role: CORE-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_IP
              value: "redisserver.teresol.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"

            - name: MSSQLRTPS_DATABASE_IP
              value: "10.90.95.85"
            - name: MSSQLRTPS_DATABASE_PORT
              value: "1433"

            - name: DATABASE_NANE
              value: "HR_DirectPayment"

            - name: MSSQLRTPS_USERNAME
              value: "JVb7gFmW3KDBw5oyWPhUbg=="

            - name: MSSQLRTPS_PASSWORD
              value: "8eK0duD7z1u/F1GCisSqVQ=="


          image: harbor.teresol.com/reporting/coremsreportbirtquarkus:0.1.9-teller
          name: coremsreportbirtquarkus
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /deployments/reports
              name: coremsreportbirtquarkus-data
          securityContext:
             capabilities:
                add: ["SYS_ADMIN"]

          resources:
           requests:
             memory: "1000Mi"
             #  cpu: "200m"
           limits:
              memory: "4000Mi"
              #  cpu: "2000m"

      restartPolicy: Always
      volumes:
        - name: coremsreportbirtquarkus-data
          hostPath:
             path: /BirtReports
             type: DirectoryOrCreate
          #          persistentVolumeClaim:
          #            claimName: coremsreportbirtquarkus-data-claim

#########################################################################
---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coremsreportbirtquarkus
  name: coremsreportbirtquarkus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32033
  selector:
    app: coremsreportbirtquarkus
  type: NodePort
