---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tlr-obc-ibc-uc10-obc-r-c-of
  name: tlr-obc-ibc-uc10-obc-r-c-of
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlr-obc-ibc-uc10-obc-r-c-of
  template:
    metadata:
      labels:
        app: tlr-obc-ibc-uc10-obc-r-c-of
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/tlr-obc-ibc-uc10-obc-r-c-of:1.1.4
          imagePullPolicy: Always
          name: tlr-obc-ibc-uc10-obc-r-c-of
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tlr-obc-ibc-uc10-obc-r-c-of
  name: tlr-obc-ibc-uc10-obc-r-c-of
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: tlr-obc-ibc-uc10-obc-r-c-of
  type: ClusterIP

#################################

#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tlr-obc-ibc-uc10-obc-r-c-of
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/tlr_obc_ibc_uc10_obc_r_c_of`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: tlr-obc-ibc-uc10-obc-r-c-of
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret
