---
apiVersion: v1
kind: Service
metadata:
  namespace: esm
  labels:
    app: coreapitieup
  name: coreapitieup
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31410
  selector:
    app: coreapitieup
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: esm
  labels:
    app: coreapitieup
  name: coreapitieup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapitieup
  template:
    metadata:
      labels:
        app: coreapitieup
    spec:
      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER
      
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"

      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"        

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: CLIENT_ID_TIEUP

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: esm-configmap-core
                  key: CLIENT_SECRET_TIEUP                          

            - name: CORE_API_TIEUP_CORS
              value: "true"

            - name: TRANSACTION_DATA_ACCESS_HOST
              value: "dataaccessmstransaction"
            - name: TRANSACTION_DATA_ACCESS_PORT
              value: "80"

            - name: TIEUP_DATA_ACCESS_HOST
              value: "dataaccessmstieup"
            - name: TIEUP_DATA_ACCESS_PORT
              value: "80"

            - name: TRANSACTION_STATUS_DATA_ACCESS_HOST
              value: "dataaccessmstransactionstatusdetail"
            - name: TRANSACTION_STATUS_DATA_ACCESS_PORT
              value: "80"

            - name: TIEUP_DETAIL_DATA_ACCESS_HOST
              value: "dataaccessmstieupdetail"
            - name: TIEUP_DETAIL_DATA_ACCESS_PORT
              value: "80"

            - name: TIEUP_AGENT_DETAIL_DATA_ACCESS_HOST
              value: "dataaccessmstieupagentdetail"
            - name: TIEUP_AGENT_DETAIL_DATA_ACCESS_PORT
              value: "80"

            - name: ACCOUNT_TITLE_DATA_ACCESS_HOST
              value: "dataaccessmstieupvalidateaccounttitle"
            - name: ACCOUNT_TITLE_DATA_ACCESS_PORT
              value: "80"

            - name: TIEUP_REPORTING_TITLE_DATA_ACCESS_HOST 
              value: "dataaccessmstieupreporting"
            - name: TIEUP_REPORTING_TITLE_DATA_ACCESS_PORT 
              value: "80"

            - name: ENCRYPTION_HOST
              value: "esmencryption"
            - name: ENCRYPTION_PORT
              value: "80"

          image: harbor.teresol.com/coreservices/coreapitieup:1.2.9
          imagePullPolicy: Always
          name: coreapitieup
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

