---
apiVersion: v1
kind: Service
metadata:
  namespace: esm
  labels:
    app: dataaccessmstieupdetail
  name: dataaccessmstieupdetail
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31407
  selector:
    app: dataaccessmstieupdetail
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: esm
  labels:
    app: dataaccessmstieupdetail
  name: dataaccessmstieupdetail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmstieupdetail
  template:
    metadata:
      labels:
        app: dataaccessmstieupdetail
    spec:
      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER

      containers:
        - env:
            
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_LOG_LEVEL



            - name: DATAACCESS_TIEUP_DETAIL_PORT
              value: "8080"
            - name: DATAACCESS_TIEUP_DETAIL_HOST
              value: "0.0.0.0"
            - name: DATAACCESS_TIEUP_DETAIL_CORS
              value: "true"
            - name: DB-KIND
              value: "mssql" 
            - name: SQL_USERNAME
              value: "rps"
            - name: SQL_PASSWORD
              value: "Rps123/?"
            - name: DB_USER
              value: "JVb7gFmW3KDBw5oyWPhUbg=="
            - name: DB_PASS
              value: "8eK0duD7z1u/F1GCisSqVQ=="
            - name: SQL_SERVER_IP
              value: "10.90.95.85"
            - name: SQL_SERVER_PORT
              value: "1433"
            - name: DATABASE_NAME
              value: "HR_DirectPayment"
            - name: SQL_DRIVER
              value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

          image: harbor.teresol.com/coreservices/dataaccessmstieupdetail:1.0.3
          imagePullPolicy: Always
          name: dataaccessmstieupdetail
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
