---
apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: esmbranch
  name: esmbranch
  namespace: esm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esmbranch
  template:
    metadata:
      labels:
        app: esmbranch
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: esm-configmap-fsm
            - configMapRef:
                name: esm-configmap-core
          env:
            - name: TOKEN_EXPIRY_IN
              value: "290s"

            - name: TOKEN_CACHE_IN
              value: "290"

          image: harbor.teresol.com/esm/esmbranch:esm-1.0.0
          imagePullPolicy: Always
          name: esmbranch
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
#########################################################
---
#Servie for esmaccount

apiVersion: v1
kind: Service
metadata:
  labels:
    app: esmbranch
  name: esmbranch
  namespace: esm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: esmbranch
  type: ClusterIP
#########################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-esm-branch
  namespace: esm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/esm/esm-branch`)
      kind: Rule
      services:
        - kind: Service
          name: esmbranch
          namespace: esm
          port: 80
  tls:
    secretName: bahl-tls-secret

