---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esmprocesstransaction
  name: esmprocesstransaction
  namespace: esm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esmprocesstransaction
  template:
    metadata:
      labels:
        app: esmprocesstransaction
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"

      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com" 

      containers:
        - envFrom:
            - configMapRef:
                name: esm-configmap-fsm
          env:
            - name: IBFT_FUND_TRANSFER
              value: "http://10.200.118.120:7801/BAHL_FCDB/proxy/BAHLEXTCHIBFT?wsdl"

            - name: IBFT_FETCH_TITLE
              value: "http://10.200.118.120:7801/BAHL_FCDB/proxy/BAHLEXT_CHTitleFetch"

            - name: API_TIEUP_HOST
              value: "http://coreapitieup"
            - name: API_TIEUP_PORT
              value: "80"

            - name: API_MIDDLEWARE_HOST
              value: "https://10.200.118.120"
            - name: API_MIDDLEWARE_PORT
              value: "7844"

            - name: PURPOSE_CODE
              value: "0401"

            - name: PURPOSE_TRANSACTION
              value: "0401"

            - name: EMAIL_ADDRESS 
              value: "Ali.RazaNaqvi@bankalhabib.com"

            - name: SFTP_IP 
              value: "10.200.118.120"

            - name: SFTP_PORT 
              value: "22"

            - name: SFTP_USER 
              value: "esbuser" 

            - name: FOLDER_PASSWORD 
              value: "admin123/?"   

            - name: SFTP_FOLDER_PATH 
              value: "/data/SftpDemo"   

            - name: EZTIMER
              value: "30s"  

            - name: TRUST_TLS_CORE_CONFIG  
              value: "true"    

            - name: INTERVAL
              value: "120"

            - name: QUARKUS_SCHEDULER_ENABLED
              value: "true"
                                                                                                                          
          image: harbor.teresol.com/esm/esmprocesstransaction:1.3.6
          imagePullPolicy: Always
          name: esmprocesstransaction
          ports:
            - containerPort: 8084
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: esmprocesstransaction
  name: esmprocesstransaction
  namespace: esm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8084
      nodePort: 30331
  selector:
    app: esmprocesstransaction
  type: NodePort
