---
- name: Replace String in File
  hosts: dev_qa
  # become: yes
  vars_files:
    - "/home/bahl/Documents/devops-document/DevOps-Practice/Ansible/vars/{{ inventory_hostname }}_vars.yaml"  # Load the variable file based on the host

  tasks:
    - name: Debug inventory_dir and inventory_hostname
      debug:
        var: inventory_dir

    - name: Debug inventory_hostname
      debug:
        var: inventory_hostname

    - name: Transfer replace_string.sh script to remote host
      copy:
        src: /home/bahl/Documents/devops-document/DevOps-Practice/Ansible/replace_string.sh
        dest: "{{ dpath }}"
        mode: '0755'

    - name: Execute the replace_string.sh script
      command: "{{ dpath }}/replace_string.sh {{ dpath }}/{{ file_name }} {{ replace_string }}"

    - name: Apply kubectl
      command: kubectl apply -f "{{ dpath }}/{{ file_name }}"
