---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapigl-crm
  name: coreapigl-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30489
  selector:
    app: coreapigl-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapigl-crm
  name: coreapigl-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapigl-crm
  template:
    metadata:
      labels:
        app: coreapigl-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_GL

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_GL

            - name: DAMS_GL_DETAIL_IP
              value: "dataaccessmsgl-crm.teresol.svc.cluster.local"
            - name: DAMS_GL_DETAIL_PORT
              value: "80"

            - name: DAMS_VALIDATE_GL_IP
              value: "dataaccessmsvalidategl-crm.teresol.svc.cluster.local"
            - name: DAMS_VALIDATE_GL_PORT
              value: "80"

            - name: CORE_MS_GL_IP
              value: "coremsgl-crm"
            - name: CORE_MS_GL_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapigl:1.3.9-crm
          imagePullPolicy: Always
          name: coreapigl-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
