---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol      
  labels:
    app: coremsexternalservice-crm
  name: coremsexternalservice-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort:  32766
  selector:
    app: coremsexternalservice-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol      
  labels:
    app: coremsexternalservice-crm
  name: coremsexternalservice-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsexternalservice-crm
  template:
    metadata:
      labels:
        app: coremsexternalservice-crm
    spec:
      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER
      nodeName: r2bcbsint23.bank.alhabib.com                            #r2bcbsint29.bank.alhabib.com
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: CORE_MS_EXTERNALSERVICE_PORT
              value: "8080"

            - name: EASTBOUND_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name: EASTBOUND_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7802"

            - name: EASTBOUND_EMAIL_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name: EASTBOUND_EMAIL_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7802"

            - name: DATAACCESS_COMMON_PROPERTIES_WEBCLIENT_IP
              value: "dataaccessmscommonproperties-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_COMMON_PROPERTIES_WEBCLIENT_PORT
              value: "80"

            - name: EASTBOUND_EXTERNAL_SERVICE_READ_TIME_OUT
              value: "66000"

            - name: EASTBOUND_CASHOVERCOUNTER_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name: EASTBOUND_CASHOVERCOUNTER_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7843"

            - name: EASTBOUND_EMAIL_MULTIATTACHMENT_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name: EASTBOUND_EMAIL_MULTIATTACHMENT_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7843"

            - name: CORE_MS_FILECREATION_WEBCLIENT_IP
              value: "coremsfile-crm"
            - name: CORE_MS_FILECREATION_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_FILESERVICE_WEBCLIENT_IP
              value: "coremsfile-crm"
            - name: CORE_MS_FILESERVICE_WEBCLIENT_PORT
              value: "80"


            - name: EASTBOUND_BIOMETRIC_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name:  EASTBOUND_BIOMETRIC_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7844"

            - name: EASTBOUND_SAFEWATCH_EXTERNAL_SERVICE_WEBCLIENT_IP
              value: "10.200.118.120"
            - name:  EASTBOUND_SAFEWATCH_EXTERNAL_SERVICE_WEBCLIENT_PORT
              value: "7801"


            - name: EASTBOUND_BIOMETRIC_DETAIL_SERVICE_WEBCLIENT_IP
              value: "10.200.131.162"
            - name:  EASTBOUND_BIOMETRIC_DETAIL_SERVICE_WEBCLIENT_PORT
              value: "7801"


            - name: LOG_LEVEL
              value: "DEBUG"


              # - name: EASTBOUND_BIOMETRIC_EXTERNAL_SERVICE_WEBCLIENT_IP
              # value: "10.200.118.120"
              # - name:  EASTBOUND_BIOMETRIC_EXTERNAL_SERVICE_WEBCLIENT_PORT
              # value: "7844"

              # - name: EASTBOUND_SAFEWATCH_EXTERNAL_SERVICE_WEBCLIENT_IP
              # value: "10.200.118.120"
              # - name:  EASTBOUND_SAFEWATCH_EXTERNAL_SERVICE_WEBCLIENT_PORT
              # value: "7801"


          image: harbor.teresol.com/teresol/coremsexternalservice:2.5.3-crm
          name: coremsexternalservice
          ports:
            - containerPort: 8080

          volumeMounts:
            - mountPath: /tmp/swiftXmlFile
              name: swiftxmlfiles-data
            - mountPath: /tmp/swiftTextFile
              name: swifttxtfiles-data
          securityContext:
             capabilities:
                add: ["SYS_ADMIN"]
      restartPolicy: Always
      volumes:
        - name: swiftxmlfiles-data
          hostPath:
             path: /swift
             type: DirectoryOrCreate
        - name: swifttxtfiles-data
          hostPath:
             path: /swifttxt
             type: DirectoryOrCreate

