---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapicard-crm
  name: coreapicard-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31744
  selector:
    app: coreapicard-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapicard-crm
  name: coreapicard-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapicard-crm
  template:
    metadata:
      labels:
        app: coreapicard-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL



            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_CARD

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_CARD

            - name: DATAACCESS_CARD_DETAIL_WEBCLIENT_IP
              value: "dataaccessmscarddetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_CARD_DETAIL_WEBCLIENT_PORT
              value: "80"



            - name: DATAACCESS_VALIDATE_CARD_WEBCLIENT_IP
              value: "dataaccessmsvalidatecard-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_VALIDATE_CARD_WEBCLIENT_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapicard:0.0.9-crm
          imagePullPolicy: Always
          name: coreapicard-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

###########################################
