---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbankdetail-crm
  name: dataaccessmsbankdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31737
  selector:
    app: dataaccessmsbankdetail-crm
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbankdetail-crm
  name: dataaccessmsbankdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbankdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbankdetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: DB_USER
              value: "U3/uuaZHqiAWJWm3DCf+qg=="

            - name: DB_PASS
              value: "CY+jVqhEuJ24nNngtOYYug=="

          image: harbor.teresol.com/teresol/dataaccessmsbankdetail:1.1.1-crm
          imagePullPolicy: Always
          name: dataaccessmsbankdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
