---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateonlauth-crm
  name: dataaccessmsvalidateonlauth-crm
spec:
  ports:
    - name: http
      ##nodePort: 31336
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsvalidateonlauth-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateonlauth-crm
  name: dataaccessmsvalidateonlauth-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidateonlauth-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidateonlauth-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap

          image: harbor.teresol.com/teresol/dataaccessmsvalidateonlauth:1.0.3-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidateonlauth-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
