---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscustomerdetail-crm
  name: dataaccessmscustomerdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31734
  selector:
    app: dataaccessmscustomerdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscustomerdetail-crm
  name: dataaccessmscustomerdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmscustomerdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmscustomerdetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_IP
              value: "redis-customer"
            - name: REDIS_PORT
              value: "6379"
          image: harbor.teresol.com/teresol/dataaccessmscustomerdetail:1.6.0-crm
          imagePullPolicy: Always
          name: dataaccessmscustomerdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
