---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmstranscodedetail-crm
  name: dataaccessmstranscodedetail-crm
spec:
  ports:
    - name: http
      #nodePort: 31374
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmstranscodedetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmstranscodedetail-crm
  name: dataaccessmstranscodedetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmstranscodedetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmstranscodedetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmstranscodedetail:1.0.4-crm
          imagePullPolicy: Always
          name: dataaccessmstranscodedetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
