---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscancelmatrix-crm
  name: dataaccessmscancelmatrix-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31465
  selector:
    app: dataaccessmscancelmatrix-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscancelmatrix-crm
  name: dataaccessmscancelmatrix-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmscancelmatrix-crm
  template:
    metadata:
      labels:
        app: dataaccessmscancelmatrix-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmscancelmatrix:0.0.4-crm
          imagePullPolicy: Always
          name: dataaccessmscancelmatrix-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
