---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  annotations:
    app.quarkus.io/commit-id: e3d604b0a01eff21c1cfd28b0b6519686c627f23
    app.quarkus.io/build-timestamp: 2022-04-12 - 05:50:07 +0000
  labels:
    app.kubernetes.io/name: dataaccessmsmessagedetail-crm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: dataaccessmsmessagedetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31726
  selector:
    app.kubernetes.io/name: dataaccessmsmessagedetail-crm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  annotations:
    app.quarkus.io/commit-id: e3d604b0a01eff21c1cfd28b0b6519686c627f23
    app.quarkus.io/build-timestamp: 2022-04-12 - 05:50:07 +0000
  labels:
    app.kubernetes.io/name: dataaccessmsmessagedetail-crm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: dataaccessmsmessagedetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataaccessmsmessagedetail-crm
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: e3d604b0a01eff21c1cfd28b0b6519686c627f23
        app.quarkus.io/build-timestamp: 2022-04-12 - 05:50:07 +0000
      labels:
        app.kubernetes.io/name: dataaccessmsmessagedetail-crm
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: BOX2_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: BOX2_DATABASE_IP

            - name: BOX3_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: BOX3_DATABASE_IP

            - name: BOX4_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: BOX4_DATABASE_IP

            - name: CPU_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: CPU_DATABASE_IP

            - name: PO_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: PO_DATABASE_IP

            - name: OBS_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: OBS_DATABASE_IP

            - name: CCARD_DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: CCARD_DATABASE_IP

            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          image: harbor.teresol.com/teresol/dataaccessmsmessagedetail:0.0.6-crm
          imagePullPolicy: Always
          name: dataaccessmsmessagedetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
