---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsprocessaccount-crm
  name: dataaccessmsprocessaccount-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32661
  selector:
    app: dataaccessmsprocessaccount-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsprocessaccount-crm
  name: dataaccessmsprocessaccount-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsprocessaccount-crm
  template:
    metadata:
      labels:
        app: dataaccessmsprocessaccount-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_PROCESSACCOUNT_IP
              value: "redis-processaccount.teresol.svc.cluster.local"
            - name: REDIS_PROCESSACCOUNT_PORT
              value: "6379"
          image: harbor.teresol.com/teresol/dataaccessmsprocessaccount:0.7.2-crm
          imagePullPolicy: Always
          name: dataaccessmsprocessaccount-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
