---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatetdr-crm
  name: dataaccessmsvalidatetdr-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30285
  selector:
    app: dataaccessmsvalidatetdr-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatetdr-crm
  name: dataaccessmsvalidatetdr-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidatetdr-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidatetdr-crm
    spec:
      #knodeSelector:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidatetdr:0.0.5-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidatetdr-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
