---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscifdetail-crm
  name: dataaccessmscifdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32581
  selector:
    app: dataaccessmscifdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscifdetail-crm
  name: dataaccessmscifdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmscifdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmscifdetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_IP
              value: "redis-cifdetail.teresol.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"

          image: harbor.teresol.com/teresol/dataaccessmscifdetail:0.9.9-crm
          imagePullPolicy: Always
          name: dataaccessmscifdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
