---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateinstrument-crm
  name: dataaccessmsvalidateinstrument-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31432 
  selector:
    app: dataaccessmsvalidateinstrument-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateinstrument-crm
  name: dataaccessmsvalidateinstrument-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidateinstrument-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidateinstrument-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidateinstrument:1.2.0-crm

          imagePullPolicy: Always
          name: dataaccessmsvalidateinstrument-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
