---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsauthorizefundstransfer-crm
  name: dataaccessmsauthorizefundstransfer-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31468
  selector:
    app: dataaccessmsauthorizefundstransfer-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsauthorizefundstransfer-crm
  name: dataaccessmsauthorizefundstransfer-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsauthorizefundstransfer-crm
  template:
    metadata:
      labels:
        app: dataaccessmsauthorizefundstransfer-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: CORE_MS_EXTERNAL_SERVICE_IP
              value: "coremsexternalservice-crm.teresol.svc.cluster.local"
            - name: CORE_MS_EXTERNAL_SERVICE_PORT
              value: "80"

          image: harbor.teresol.com/teresol/dataaccessmsauthorizefundstransfer:0.1.6-crm
          imagePullPolicy: Always
          name: dataaccessmsauthorizefundstransfer-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
