---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dataaccessmsvalidatecountry-crm
  name: dataaccessmsvalidatecountry-crm
  namespace: teresol
spec:
  ports:
    - name: http
      nodePort: 32117
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsvalidatecountry-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataaccessmsvalidatecountry-crm
  name: dataaccessmsvalidatecountry-crm
  namespace: teresol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidatecountry-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidatecountry-crm
    spec:
      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidatecountry:1.0.6-teller
          imagePullPolicy: Always
          name: dataaccessmsvalidatecountry-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
