---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbillercompanydetail-crm
  name: dataaccessmsbillercompanydetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      #      nodePort: 32750
  selector:
    app: dataaccessmsbillercompanydetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbillercompanydetail-crm
  name: dataaccessmsbillercompanydetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbillercompanydetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbillercompanydetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbillercompanydetail:1.0.1-crm
          imagePullPolicy: Always
          name: dataaccessmsbillercompanydetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
