---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsdebarredlistdetail-crm
  name: dataaccessmsdebarredlistdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      #nodePort: 31390
  selector:
    app: dataaccessmsdebarredlistdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsdebarredlistdetail-crm
  name: dataaccessmsdebarredlistdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsdebarredlistdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsdebarredlistdetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsdebarredlistdetail:1.0.9-crm
          imagePullPolicy: Always
          name: dataaccessmsdebarredlistdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
