---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsopenbatch-crm
  name: dataaccessmsopenbatch-crm
spec:

  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31436 
  selector:
    app: dataaccessmsopenbatch-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsopenbatch-crm
  name: dataaccessmsopenbatch-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsopenbatch-crm
  template:
    metadata:
      labels:
        app: dataaccessmsopenbatch-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsopenbatch:0.0.3-crm
          imagePullPolicy: Always
          name: dataaccessmsopenbatch-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
