---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbulkinstrument-crm
  name: dataaccessmsbulkinstrument-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31767
  selector:
    app: dataaccessmsbulkinstrument-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbulkinstrument-crm
  name: dataaccessmsbulkinstrument-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbulkinstrument-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbulkinstrument-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbulkinstrument:1.0.3-crm
          imagePullPolicy: Always
          name: dataaccessmsbulkinstrument-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
