---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatecnicrestrict-crm
  name: dataaccessmsvalidatecnicrestrict-crm
spec:
  ports:
    - name: http
      nodePort: 32617
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsvalidatecnicrestrict-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatecnicrestrict-crm
  name: dataaccessmsvalidatecnicrestrict-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidatecnicrestrict-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidatecnicrestrict-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidatecnicrestrict:1.0.1-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidatecnicrestrict-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
