---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol     
  labels:
    app: dataaccessmstrancoderestrictdetail-crm
  name: dataaccessmstrancoderestrictdetail-crm
spec:
  ports:
    - name: http
      #nodePort: 31302
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmstrancoderestrictdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol    
  labels:
    app: dataaccessmstrancoderestrictdetail-crm
  name: dataaccessmstrancoderestrictdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmstrancoderestrictdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmstrancoderestrictdetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmstrancoderestrictdetail:1.0.2-crm
          imagePullPolicy: Always
          name: dataaccessmstrancoderestrictdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
