---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbulkclearing-crm
  name: dataaccessmsbulkclearing-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31425
  selector:
    app: dataaccessmsbulkclearing-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbulkclearing-crm
  name: dataaccessmsbulkclearing-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbulkclearing-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbulkclearing-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "redisserver.teresol.svc.cluster.local"

          image: harbor.teresol.com/teresol/dataaccessmsbulkclearing:1.0.5-crm
          imagePullPolicy: Always
          name: dataaccessmsbulkclearing-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
