---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: redisserver-inwardpolling
  name: redisserver-inwardpolling
spec:
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: redisserver-inwardpolling

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: redisserver-inwardpolling
  name: redisserver-inwardpolling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisserver-inwardpolling
  template:
    metadata:
      labels:
        app: redisserver-inwardpolling
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      #nodeSelector:
        #kubernetes.io/role: CORE-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"

          image: harbor.teresol.com/teresol/redisserver:7.0
          imagePullPolicy: Always
          name: redisserver-inwardpolling
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP

