---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol      
  labels:
    app: coreapicharges-crm
  name: coreapicharges-crm
spec:
  ports:
    - name: http
      nodePort: 31988
      port: 80
      targetPort: 8080
  selector:
    app: coreapicharges-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol     
  labels:
    app: coreapicharges-crm
  name: coreapicharges-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapicharges-crm
  template:
    metadata:
      labels:
        app: coreapicharges-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_CHARGES

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_CHARGES

            - name: DATAACCESS_MS_CHARGESDETAIL_IP
              value: "dataaccessmschargesdetail-crm"
            - name: DATAACCESS_MS_CHARGESDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATECHARGES_IP
              value: "dataaccessmsvalidatecharges-crm"
            - name: DATAACCESS_MS_VALIDATECHARGES_PORT
              value: "80"

            - name: DATAACCESS_MS_TRANSCODEDETAIL_IP
              value: "dataaccessmstranscodedetail-crm"
            - name: DATAACCESS_MS_TRANSCODEDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_PARAMDETAIL_IP
              value: "dataaccessmsparamsdetails-crm"
            - name: DATAACCESS_MS_PARAMDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_CURRENCYDETAIL_IP
              value: "dataaccessmscurrencydetail-crm"
            - name: DATAACCESS_MS_CURRENCYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_GLDETAIL_IP
              value: "dataaccessmsgl-crm"
            - name: DATAACCESS_MS_GLDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_CUSTOMERDETAIL_IP
              value: "dataaccessmscustomerdetail-crm"
            - name: DATAACCESS_MS_CUSTOMERDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATE_PRODUCT_IP
              value: "dataaccessmsvalidateproduct-crm"
            - name: DATAACCESS_MS_VALIDATE_PRODUCT_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapicharges:0.1.3-crm
          imagePullPolicy: Always
          name: coreapicharges-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
