---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapibranch-crm
  name: coreapibranch-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31987
  selector:
    app: coreapibranch-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapibranch-crm
  name: coreapibranch-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapibranch-crm
  template:
    metadata:
      labels:
        app: coreapibranch-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_BRANCH

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_BRANCH

            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: DATAACCESS_BRANCH_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsbranchdetail-crm"
            - name: DATAACCESS_BRANCH_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VALIDATE_BRANCH_WEBCLIENT_IP
              value: "dataaccessmsvalidatebranch-crm"
            - name: DATAACCESS_VALIDATE_BRANCH_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_PARAMS_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsparamsdetails-crm"
            - name: DATAACCESS_PARAMS_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_ACCOUNTOPENINGBRANCH_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsaccountopeningbranchdetail-crm"
            - name: DATAACCESS_ACCOUNTOPENINGBRANCH_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VALIDATE_MODAVTVTL_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsvalidatemodavtv-crm"
            - name: DATAACCESS_VALIDATE_MODAVTVTL_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: CLIENT_VALIDATE_USER_SERVICE_WEBCLIENT_IP
              value: "aaa-validate-user-data-access-service-crm.aaa.svc.cluster.local"
            - name: CLIENT_VALIDATE_USER_SERVICE_WEBCLIENT_PORT
              value: "8080"


          image: harbor.teresol.com/teresol/coreapibranch:0.1.7-crm
          imagePullPolicy: Always
          name: coreapibranch-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
