---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapiexternalmessages-crm
  name: coreapiexternalmessages-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31725
  selector:
    app: coreapiexternalmessages-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapiexternalmessages-crm
  name: coreapiexternalmessages-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapiexternalmessages-crm
  template:
    metadata:
      labels:
        app: coreapiexternalmessages-crm
    spec:
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_EXTERNALMESSAGES

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_EXTERNALMESSAGES

            - name: DATAACCESS_MS_SWIFTMESSAGEDETAIL_IP
              value: "dataaccessmsswiftmessagedetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_SWIFTMESSAGEDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_MESSAGEDETAIL_IP
              value: "dataaccessmsmessagedetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_MESSAGEDETAIL_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapiexternalmessages:0.0.4-crm
          imagePullPolicy: Always
          name: coreapiexternalmessages-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
