---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coremscancelinstrument-crm
  name: coremscancelinstrument-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: coremscancelinstrument-crm
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coremscancelinstrument-crm
  name: coremscancelinstrument-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremscancelinstrument-crm
  template:
    metadata:
      labels:
        app: coremscancelinstrument-crm
    spec:
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL


            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "redisserver"

            - name: DATAACCESS_BULK_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsbulkinstrument-crm"
            - name: DATAACCESS_BULK_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coremscancelinstrument:1.0.0-crm
          imagePullPolicy: Always
          name: coremscancelinstrument-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
