---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coremsoutwardrelease-crm
  name: coremsoutwardrelease-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: coremsoutwardrelease-crm
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coremsoutwardrelease-crm
  name: coremsoutwardrelease-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsoutwardrelease-crm
  template:
    metadata:
      labels:
        app: coremsoutwardrelease-crm
    spec:
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL


            - name: CORE_MS_MATRIX_IP
              value: "coremsmatrix-crm.teresol.svc.cluster.local"
            - name: CORE_MS_MATRIX_PORT
              value: "80"

            - name: DATAACCESS_OUTWARD_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsoutwardinstrument-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_OUTWARD_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsvalidateinstrument-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "redisserver-inwardpolling.teresol.svc.cluster.local"

            - name: CORE_MS_FT_IP
              value: "coremsfundstransfer-crm.teresol.svc.cluster.local"
            - name: CORE_MS_FT_PORT
              value: "80"

            - name: DATAACCESS_BULK_CLEARING_WEBCLIENT_IP
              value: "dataaccessmsbulkclearing-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_BULK_CLEARING_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrument-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrumentconsolidated-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VOUCHER_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsvoucherdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_VOUCHER_DETAIL_WEBCLIENT_PORT
              value: "80"
              

          image: harbor.teresol.com/teresol/coremsoutwardrelease:1.0.1-crm
          imagePullPolicy: Always
          name: coremsoutwardrelease-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
