---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapiexternalservice-crm
  name: coreapiexternalservice-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32395
  selector:
    app: coreapiexternalservice-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapiexternalservice-crm
  name: coreapiexternalservice-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapiexternalservice-crm
  template:
    metadata:
      labels:
        app: coreapiexternalservice-crm
      name: coreapiexternalservice-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_EXTERNALSERVICE

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                 configMapKeyRef:
                   name: coreapi-svc-configmap
                   key: CLIENT_SECRET_EXTERNALSERVICE

            - name: DATAACCESS_BILLER_COMPANY_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsbillercompanydetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_BILLER_COMPANY_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_EXTERNALSERVICE_WEBCLIENT_IP
              value: "coremsexternalservice-crm"
            - name: CORE_MS_EXTERNALSERVICE_WEBCLIENT_PORT
              value: "80"

              #- name: CORE_MS_EXTERNALSERVICEBILLER_WEBCLIENT_IP
              #value: "coremsexternalservice-crm.teresol.svc.cluster.local"
              #- name: CORE_MS_EXTERNALSERVICEBILLER_WEBCLIENT_PORT
              #value: "80"


          image: harbor.teresol.com/teresol/coreapiexternalservice:1.8.9-crm
          imagePullPolicy: Always
          name: coreapiexternalservice-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
