---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapifundstransferbiller-crm
  name: coreapifundstransferbiller-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32336
  selector:
    app: coreapifundstransferbiller-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapifundstransferbiller-crm
  name: coreapifundstransferbiller-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapifundstransferbiller-crm
  template:
    metadata:
      labels:
        app: coreapifundstransferbiller-crm
    spec:
      #nodeSelector:
        #kubernetes.io/role: CORE-WORKER
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
               configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_FUNDTRANSFERBILLER

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_FUNDTRANSFERBILLER


            - name: CORE_API_FUNDSTRANSFER_MS_IP
              value: "coremsfundstransferbiller-crm.teresol.svc.cluster.local"

            - name: CORE_API_FUNDSTRANSFER_MS_PORT
              value: "80"

            - name: VOUCHER_DETAIL_IP
              value: "dataaccessmsvoucherdetail-crm.teresol.svc.cluster.local"

            - name: VOUCHER_DETAIL_PORT
              value: "80"

            - name: VALIDATE_TRANSACTION_IP
              value: "dataaccessmsvalidatetransaction-crm.teresol.svc.cluster.local"

            - name: VALIDATE_TRANSACTION_PORT
              value: "80"

            - name: FUNDS_TRANSFER_DETAIL_IP
              value: "dataaccessmsfundstransferdetail-crm.teresol.svc.cluster.local"

            - name: FUNDS_TRANSFER_DETAIL_PORT
              value: "80"

            - name: CORE_API_FUNDSTRANSFER_ROOT_PATH
              value: "core-api-fundsTransferBiller/v3"

            - name: CORE_API_FUNDSTRANSFER_MS_BASEPATH
              value: "core-ms-fundsTransferBiller/v3"

            - name: CORE_MS_FUNDSTRANSFER_WEBCLIENT_RTIMEOUT
              value: "70000"

            - name: QUARKUS_LOG_LEVEL
              value: "DEBUG"

#            - name: quarkus.log.category."iio.quarkus.oidc".level
            - name: QUARKUS_LOG_CATEGORY__IO_QUARKUS_OIDC__LEVEL
              value: "TRACE"

          image: harbor.teresol.com/teresol/coreapifundstransferbiller:1.1.5-teller
          imagePullPolicy: Always
          name: coreapifundstransferbiller-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

