---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coremsuploadnift-crm
  name: coremsuploadnift-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31413
  selector:
    app: coremsuploadnift-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coremsuploadnift-crm
  name: coremsuploadnift-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsuploadnift-crm
  template:
    metadata:
      labels:
        app: coremsuploadnift-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dataaccess-svc-configmap
                  key: QUARKUS_LOG_LEVEL


            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "redisserver"

            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrument-crm"
            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_PORT
              value: "79"

            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrumentconsolidated-crm"
            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsvalidateinstrument-crm"
            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsinstrument-crm"
            - name: DATAACCESS_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_ACCOUNT_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsaccountinstrument-crm"
            - name: DATAACCESS_ACCOUNT_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_ACCOUNT_DETAIL_IP
              value: "dataaccessmsaccountdetail-crm" 
            - name: DATAACCESS_ACCOUNT_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_VOUCHER_DETAIL_IP
              value: "dataaccessmsvoucherdetail-crm"
            - name: DATAACCESS_VOUCHER_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_BRANCH_DETAIL_IP
              value: "dataaccessmsbranchdetail-crm"
            - name: DATAACCESS_BRANCH_DETAIL_PORT
              value: "80"

            - name: CORE_MS_FILE_IP
              value: "coremsfile-crm"
            - name: CORE_MS_FILE_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coremsuploadnift:1.0.8-crm
          imagePullPolicy: Always
          name: coremsuploadnift-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
