---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coremsinwardreleasepolling-crm
  name: coremsinwardreleasepolling-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31765
  selector:
    app: coremsinwardreleasepolling-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coremsinwardreleasepolling-crm
  name: coremsinwardreleasepolling-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsinwardreleasepolling-crm
  template:
    metadata:
      labels:
        app: coremsinwardreleasepolling-crm
    spec:
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL


            - name: DATAACCESS_BULK_CLEARING_WEBCLIENT_IP
              value: "dataaccessmsbulkclearing-crm"
            - name: DATAACCESS_BULK_CLEARING_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsinstrument-crm"
            - name: DATAACCESS_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsvalidateinstrument-crm"
            - name: DATAACCESS_VALIDATE_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_OUTWARD_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsoutwardinstrument-crm"
            - name: DATAACCESS_OUTWARD_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_FT_IP
              value: "coremsfundstransfer-crm"
            - name: CORE_MS_FT_PORT
              value: "80"

            - name: CORE_MS_MATRIX_IP
              value: "coremsmatrix-crm"
            - name: CORE_MS_MATRIX_PORT
              value: "80"

            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrumentconsolidated-crm"
            - name: DATAACCESS_CLEARING_INSTRUMENT_CONSOLIDATED_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrument-crm"
            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: MAX_RETRY_ATTEMPTS
              value: "115"

            - name: MAX_RETRY_TIME
              value: "600"

            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "redisserver-inwardpolling"

          image: harbor.teresol.com/teresol/coremsinwardreleasepolling:1.0.2-crm
          imagePullPolicy: Always
          name: coremsinwardreleasepolling-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
#####################################

