---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol      
  labels:
    app: coreapisetup-crm
  name: coreapisetup-crm
spec:
  ports:
    - name: http
      nodePort: 31091
      port: 80
      targetPort: 8080
  selector:
    app: coreapisetup-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol     
  labels:
    app: coreapisetup-crm
  name: coreapisetup-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapisetup-crm
  template:
    metadata:
      labels:
        app: coreapisetup-crm
    spec:
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_SETUP

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_SETUP

            - name: DATAACCESS_MS_SETUPACCOUNTDETAIL_IP
              value: "dataaccessmssetupaccountdetail-crm"
            - name: DATAACCESS_MS_SETUPACCOUNTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_SETUPALERTDETAIL_IP
              value: "dataaccessmssetupalertdetail-crm"
            - name: DATAACCESS_MS_SETUPALERTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_SETUPCREDITDETAIL_IP
              value: "dataaccessmssetupcreditdetail-crm"
            - name: DATAACCESS_MS_SETUPCREDITDETAIL_PORT
              value: "80"
              
            - name: DATAACCESS_MS_SETUPDOCUMENTDETAIL_IP
              value: "dataaccessmssetupdocumentdetail-crm"
            - name: DATAACCESS_MS_SETUPDOCUMENTDETAIL_PORT
              value: "80"
              
            - name: DATAACCESS_MS_SETUPFILEDETAIL_IP
              value: "dataaccessmssetupfiledetail-crm"
            - name: DATAACCESS_MS_SETUPFILEDETAIL_PORT
              value: "80"
              
            - name: DATAACCESS_MS_SETUPLIMITDETAIL_IP
              value: "dataaccessmssetuplimitdetail-crm"
            - name: DATAACCESS_MS_SETUPLIMITDETAIL_PORT
              value: "80"
              
            - name: DATAACCESS_MS_SETUPCUSTOMERDETAIL_IP
              value: "dataaccessmssetupcustomerdetail-crm"
            - name: DATAACCESS_MS_SETUPCUSTOMERDETAIL_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapisetup:1.5.4-crm
          imagePullPolicy: Always
          name: coreapisetup-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

