---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapibiometric-crm
  name: coreapibiometric-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30421
  selector:
    app: coreapibiometric-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapibiometric-crm
  name: coreapibiometric-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapibiometric-crm
  template:
    metadata:
      labels:
        app: coreapibiometric-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_FUNDTRANSFER

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_FUNDTRANSFER

            - name: DATAACCESS_BIOMETRIC_DETAIL_HOST
              value: "dataaccessmsbiometricdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_BIOMETRIC_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_BIOMETRIC_VALIDATE_HOST
              value: "dataaccessmsvalidatebiometric-crm"
            - name: DATAACCESS_BIOMETRIC_VALIDATE_PORT
              value: "80"

            - name: DATAACCESS_BIOSETUP_HOST
              value: "dataaccessmssetupbiodetail-crm"
            - name: DATAACCESS_BIOSETUP_PORT
              value: "80"

            - name: CORE_MS_EXTERNAL_SERVICE_IP
              value: "coremsexternalservice-crm"
            - name: CORE_MS_EXTERNAL_SERVICE_PORT
              value: "80"
            
            - name: DATAACCESS_MS_BIOSETUP_HOST
              value: "dataaccessmssetupbiodetail-crm"
            - name: DATAACCESS_MS_BIOSETUP_PORT
              value: "80"
            
            - name: DATAACCESS_MS_COUNTRYDETAIL_HOST 
              value: "dataaccessmscountrydetail-crm"
            - name: DATAACCESS_MS_COUNTRYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_EXCEPTIONDETAIL_HOST
              value: "dataaccessmsexceptiondetail-crm"
            - name: DATAACCESS_MS_EXCEPTIONDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATE_ACCOUNT_HOST
              value: "dataaccessmsvalidateaccount-crm"
            - name: DATAACCESS_MS_VALIDATE_ACCOUNT_PORT
              value: "80"

            - name: DATAACCESS_MS_CUSTOMER_DETAIL_HOST
              value: "dataaccessmscustomerdetail-crm"
            - name: DATAACCESS_MS_CUSTOMER_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_SETUP_CUSTOMER_DETAIL_HOST
              value: "dataaccessmssetupcustomerdetail-crm"
            - name: DATAACCESS_MS_SETUP_CUSTOMER_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATE_PARAMS_HOST
              value: "dataaccessmsvalidateparams-crm"
            - name: DATAACCESS_MS_VALIDATE_PARAMS_PORT
              value: "80"

            - name: DATAACCESS_MS_SETUP_ACCOUNT_DETAIL_HOST
              value: "dataaccessmssetupaccountdetail-crm"
            - name: DATAACCESS_MS_SETUP_ACCOUNT_DETAIL_PORT 
              value: "80"

            - name: DATAACCESS_MS_ACCOUNT_DETAIL_HOST
              value: "dataaccessmsaccountdetail-crm"
            - name: DATAACCESS_MS_ACCOUNT_DETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_PARAMS_DETAILS_HOST
              value: "dataaccessmsparamsdetails-crm"
            - name: DATAACCESS_MS_PARAMS_DETAILS_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapibiometric:1.9.2-crm
          imagePullPolicy: Always
          name: coreapibiometric-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
