---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapimiscsetup-crm
  name: coreapimiscsetup-crm
spec:
  ports:
    - name: http
      nodePort: 31991
      port: 80
      targetPort: 8080
  selector:
    app: coreapimiscsetup-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapimiscsetup-crm
  name: coreapimiscsetup-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapimiscsetup-crm
  template:
    metadata:
      labels:
        app: coreapimiscsetup-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_MISCSETUP

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_MISCSETUP


            - name: DATAACCESS_MS_TRANSACTIONDETAIL_PORT
              value: "80"
            - name: DATAACCESS_MS_TRANSATIONDETAIL_IP
              value: "dataaccessmstranscodedetail-crm.teresol.svc.cluster.local"

            - name: DATAACCESS_MS_DEPARTMENTDETAIL_IP
              value: "dataaccessmsdepartmentdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_DEPARTMENT_PORT
              value: "80"

            - name: DATAACCESS_MS_MISCCHARGESDETAIL_IP
              value: "dataaccessmsmiscchargedetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_MISCCHARGESDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEDEBARREDLIST_IP
              value: "dataaccessmsvalidatedebarredlistsetup-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_VALIDATEDEBARREDLIST_PORT
              value: "80"

            - name: DATAACCESS_MS_CHARGESSPECIALDETAIL_IP
              value: "dataaccessmschargesspecialdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_CHARGESSPECIALDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_REASONDETAIL_IP
              value: "dataaccessmsreasondetail-crm"
            - name: DATAACCESS_MS_REASONDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_MODAVTVTLDETAIL_IP
              value: "dataaccessmsmodavtvdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_MODAVTVTLDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEREASONDETAIL_IP
              value: "dataaccessmsvalidatereasondetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_VALIDATEREASONDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATETRANSCODEDETAIL_IP
              value: "dataaccessmsvalidatetranscodedetail-crm"
            - name: DATAACCESS_MS_VALIDATETRANSCODEDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_CHARGESDETAIL_IP
              value: "dataaccessmschargesdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_CHARGESDETAIL_PORT
              value: "80"

            - name: DATAACESS_MS_VALIDATEMODAVTV_IP
              value: "dataaccessmsvalidatemodavtv-crm"
            - name: DATAACESS_MS_VALIDATEMODAVTV_PORT
              value: "80"

            - name: DATAACCESS_MS_DEBARREDLISTDETAIL_IP
              value: "dataaccessmsdebarredlistdetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_DEBARREDLISTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_COUNTRYDETAIL_IP
              value: "dataaccessmscountrydetail-crm"
            - name: DATAACCESS_MS_COUNTRYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_BIOCAPTUREDETAIL_IP
              value: "dataaccessmsbiocapturedetail-crm"
            - name: DATAACCESS_MS_BIOCAPTUREDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_PREVIOUSBALANCE_IP
              value: "dataaccessmspreviousbalance-crm"
            - name: DATAACCESS_MS_PREVIOUSBALANCE_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEHASHSEED_IP
              value: "dataaccessmsvalidatehashseed-crm"
            - name: DATAACCESS_MS_VALIDATEHASHSEED_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATETRANSRESTRICT_IP
              value: "dataaccessmsvalidatetransrestrict-crm"
            - name: DATAACCESS_MS_VALIDATETRANSRESTRICT_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATECOUNTRYDETAIL_IP
              value: "dataaccessmsvalidatecountry-crm"
            - name: DATAACCESS_MS_VALIDATECOUNTRYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEBIOCAPTUREDETAIL_IP
              value: "dataaccessmsvalidatebiocapturedetail-crm"
            - name: DATAACCESS_MS_VALIDATEBIOCAPTUREDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEACTIVITYDETAIL_IP
              value: "dataaccessmsvalidateactivitydetail-crm"
            - name: DATAACCESS_MS_VALIDATEACTIVITYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_TRANCODERESTRICTDETAIL_IP
              value: "dataaccessmstrancoderestrictdetail-crm"
            - name: DATAACCESS_MS_TRANCODERESTRICTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_PARAMSDETAILS_IP
              value: "dataaccessmsparamsdetails-crm"
            - name: DATAACCESS_MS_PARAMSDETAILS_PORT
              value: "80"

            - name: DATAACCESS_MS_EXCEPTIONDETAIL_IP
              value: "dataaccessmsexceptiondetail-crm"
            - name: DATAACCESS_MS_EXCEPTIONDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATECNICRESTRICT_IP
              value: "dataaccessmsvalidatecnicrestrict-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_MS_VALIDATECNICRESTRICT_PORT
              value: "80"

            - name: DATAACCESS_MS_IDDOCDETAIL_IP
              value: "dataaccessmsiddocdetail-crm"
            - name: DATAACCESS_MS_IDDOCDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEVERSION_IP
              value: "dataaccessmsvalidateversion-crm"
            - name: DATAACCESS_MS_VALIDATEVERSION_PORT
              value: "80"

            - name: DATAACCESS_MS_CLEARINGSETTLEMENTDETAIL_IP
              value: "dataaccessmsclearingsettlementdetail-crm"
            - name: DATAACCESS_MS_CLEARINGSETTLEMENTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEPARAMS_IP
              value: "dataaccessmsvalidateparams-crm"
            - name: DATAACCESS_MS_VALIDATEPARAMS_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATECHARGES_IP
              value: "dataaccessmsvalidatecharges-crm"
            - name: DATAACCESS_MS_VALIDATECHARGES_PORT
              value: "80"

            - name: DATAACCESS_MS_BENEFICIARYDETAIL_IP
              value: "dataaccessmsbeneficiarydetail-crm"
            - name: DATAACCESS_MS_BENEFICIARYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_ACTIVITYDETAIL_IP
              value: "dataaccessmsactivitydetail-crm"
            - name: DATAACCESS_MS_ACTIVITYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_ONLAUTHDETAIL_IP
              value: "dataaccessmsonlauthdetail-crm"
            - name: DATAACCESS_MS_ONLAUTHDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEONLAUTH_IP
              value: "dataaccessmsvalidateonlauth-crm"
            - name: DATAACCESS_MS_VALIDATEONLAUTH_PORT
              value: "80"

            - name: DATAACCESS_MS_CATEGORYDETAIL_IP
              value: "dataaccessmscategorydetail-crm"
            - name: DATAACCESS_MS_CATEGORYDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_WITHHOLDINGTXTDETAIL_IP
              value: "dataaccessmswithholdingtxtdetail-crm"
            - name: DATAACCESS_MS_WITHHOLDINGTXTDETAIL_PORT
              value: "80"

            - name: DATAACCESS_MS_COMMONPROPERTIES_IP
              value: "dataaccessmscommonproperties-crm"
            - name: DATAACCESS_MS_COMMONPROPERTIES_PORT
              value: "80"

            - name: DATAACCESS_MS_VALIDATEBENEFICIARY_IP
              value: "dataaccessmsvalidatebeneficiary-crm"
            - name: DATAACCESS_MS_VALIDATEBENEFICIARY_PORT
              value: "80"

            - name: DATAACCESS_MS_COURIER_IP
              value: "dataaccessmscourier-crm"
            - name: DATAACCESS_MS_COURIER_PORT
              value: "80"

            - name: DATAACCESS_ACCOUNT_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsaccountdetail-crm"
            - name: DATAACCESS_ACCOUNT_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_MS_FX_DEAL_IP
              value: "dataaccessmsfxdealdetail-crm"
            - name: DATAACCESS_MS_FX_DEAL_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapimiscsetup:1.4.4-crm
          imagePullPolicy: Always
          name: coreapimiscsetup-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
