---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsexecutefundstransfer-crm
  name: dataaccessmsexecutefundstransfer-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30870
  selector:
    app: dataaccessmsexecutefundstransfer-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsexecutefundstransfer-crm
  name: dataaccessmsexecutefundstransfer-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsexecutefundstransfer-crm
  template:
    metadata:
      labels:
        app: dataaccessmsexecutefundstransfer-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap

          env:
            - name: CORE_MS_EXTERNAL_SERVICE_IP
              value: "coremsexternalservice-crm.teresol.svc.cluster.local"
            - name: CORE_MS_EXTERNAL_SERVICE_PORT
              value: "80"

            - name: TYPE1
              value: type1

            - name: REDIS_FT_IP 
              value: "redisserver-executeft.teresol.svc.cluster.local"
            - name: REDIS_FT_PORT
              value: "6379"

          image: harbor.teresol.com/teresol/dataaccessmsexecutefundstransfer:0.3.3-crm
          imagePullPolicy: Always
          name: dataaccessmsexecutefundstransfer-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
