---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateparams-crm
  name: dataaccessmsvalidateparams-crm
spec:
  ports:
    - name: http
      nodePort: 32659
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsvalidateparams-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidateparams-crm
  name: dataaccessmsvalidateparams-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidateparams-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidateparams-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidateparams:1.0.8-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidateparams-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
