---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsinstrument-crm
  name: dataaccessmsinstrument-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31429
  selector:
    app: dataaccessmsinstrument-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsinstrument-crm
  name: dataaccessmsinstrument-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsinstrument-crm
  template:
    metadata:
      labels:
        app: dataaccessmsinstrument-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsinstrument:1.0.7-crm
          imagePullPolicy: Always
          name: dataaccessmsinstrument-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
