---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsfxdealdetail-crm
  name: dataaccessmsfxdealdetail-crm
spec:
  ports:
    - name: http
      #nodePort: 32270
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsfxdealdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsfxdealdetail-crm
  name: dataaccessmsfxdealdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsfxdealdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsfxdealdetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsfxdealdetail:1.0.0-crm
          imagePullPolicy: Always
          name: dataaccessmsfxdealdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
