---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsadvices-crm
  name: dataaccessmsadvices-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31424
  selector:
    app: dataaccessmsadvices-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsadvices-crm
  name: dataaccessmsadvices-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsadvices-crm
  template:
    metadata:
      labels:
        app: dataaccessmsadvices-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsadvices:1.1.0-crm
          imagePullPolicy: Always
          name: dataaccessmsadvices-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
