---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsclearinginstrumentimages-crm
  name: dataaccessmsclearinginstrumentimages-crm
spec:
  ports:
    - name: http
      nodePort: 31427
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsclearinginstrumentimages-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsclearinginstrumentimages-crm
  name: dataaccessmsclearinginstrumentimages-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsclearinginstrumentimages-crm
  template:
    metadata:
      labels:
        app: dataaccessmsclearinginstrumentimages-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsclearinginstrumentimages:1.0.1-crm
          imagePullPolicy: Always
          name: dataaccessmsclearinginstrumentimages-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
