---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsreasondetail-crm
  name: dataaccessmsreasondetail-crm
spec:
  ports:
    - name: http
      #nodePort: 31380
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsreasondetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsreasondetail-crm
  name: dataaccessmsreasondetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsreasondetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsreasondetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsreasondetail:1.1.1-crm
          imagePullPolicy: Always
          name: dataaccessmsreasondetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
