---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmslimitdetail-crm
  name: dataaccessmslimitdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      #      nodePort: 31346
  selector:
    app: dataaccessmslimitdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmslimitdetail-crm
  name: dataaccessmslimitdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmslimitdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmslimitdetail-crm
    spec:
      #knodeSelector:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmslimitdetail:0.1.0-crm
          imagePullPolicy: Always
          name: dataaccessmslimitdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

