---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatebank-crm
  name: dataaccessmsvalidatebank-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31773
  selector:
    app: dataaccessmsvalidatebank-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsvalidatebank-crm
  name: dataaccessmsvalidatebank-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidatebank-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidatebank-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap

          env:
            - name: REDIS_IP
              value: "redis-customer"
            - name: REDIS_PORT
              value: "6379"

          image: harbor.teresol.com/teresol/dataaccessmsvalidatebank:1.0.0-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidatebank-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

