---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscompanydetail-crm
  name: dataaccessmscompanydetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31750
  selector:
    app: dataaccessmscompanydetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscompanydetail-crm
  name: dataaccessmscompanydetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmscompanydetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmscompanydetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmscompanydetail:0.0.9-crm
          imagePullPolicy: Always
          name: dataaccessmscompanydetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
