---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmschargesdetail-crm
  name: dataaccessmschargesdetail-crm
spec:
  ports:
    - name: http
      #nodePort: 31385
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmschargesdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmschargesdetail-crm
  name: dataaccessmschargesdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmschargesdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmschargesdetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmschargesdetail:1.1.4-crm
          imagePullPolicy: Always
          name: dataaccessmschargesdetail-crm
          ports:
            - containerPort: 8080

              name: http
              protocol: TCP
