---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsdepartmentdetail-crm
  name: dataaccessmsdepartmentdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      #nodePort: 31378
  selector:
    app: dataaccessmsdepartmentdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsdepartmentdetail-crm
  name: dataaccessmsdepartmentdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsdepartmentdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsdepartmentdetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsdepartmentdetail:1.0.2-crm
          imagePullPolicy: Always
          name: dataaccessmsdepartmentdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
