---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol     
  labels:
    app: dataaccessmsvalidatetranscodedetail-crm
  name: dataaccessmsvalidatetranscodedetail-crm
spec:
  ports:
    - name: http
      #nodePort: 31391
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsvalidatetranscodedetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol     
  labels:
    app: dataaccessmsvalidatetranscodedetail-crm
  name: dataaccessmsvalidatetranscodedetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsvalidatetranscodedetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsvalidatetranscodedetail-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsvalidatetranscodedetail:1.0.2-crm
          imagePullPolicy: Always
          name: dataaccessmsvalidatetranscodedetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
