---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbiocapturedetail-crm
  name: dataaccessmsbiocapturedetail-crm
spec:
  ports:
    - name: http
      nodePort:  30508
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsbiocapturedetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbiocapturedetail-crm
  name: dataaccessmsbiocapturedetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbiocapturedetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbiocapturedetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbiocapturedetail:1.0.2-crm
          imagePullPolicy: Always
          name: dataaccessmsbiocapturedetail-crm
          ports:
            - containerPort: 8080

              name: http
              protocol: TCP
