---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsexecutefundstransferbiller-crm
  name: dataaccessmsexecutefundstransferbiller-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
     # nodePort: 30396
  selector:
    app: dataaccessmsexecutefundstransferbiller-crm
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsexecutefundstransferbiller-crm
  name: dataaccessmsexecutefundstransferbiller-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsexecutefundstransferbiller-crm
  template:
    metadata:
      labels:
        app: dataaccessmsexecutefundstransferbiller-crm
    spec:
     
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: CORE_MS_EXTERNAL_SERVICE_IP
              value: "coremsexternalservice.teresol.svc.cluster.local"
            - name: CORE_MS_EXTERNAL_SERVICE_PORT
              value: "80"

            - name: TYPE1
              value: type1
            - name: DATAACCESS_MS_EXECUTEFUNDSTRANSFER_ROOT_PATH
              value: "dataaccess-ms-fundsTransferBiller/v3"
            - name: CORE_MS_EXTERNAL_SERVICE_RDTIMEOUT
              value: "66000"
            - name: TRANSACTION_TIMEOUT
              value: "70"
          image: harbor.teresol.com/teresol/dataaccessmsexecutefundstransferbiller:1.1.9-teller
          imagePullPolicy: Always
          name: dataaccessmsexecutefundstransferbiller-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
