---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsauthorizefundstransferbiller-crm
  name: dataaccessmsauthorizefundstransferbiller-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    #  nodePort: 30395
  selector:
    app: dataaccessmsauthorizefundstransferbiller-crm
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsauthorizefundstransferbiller-crm
  name: dataaccessmsauthorizefundstransferbiller-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsauthorizefundstransferbiller-crm
  template:
    metadata:
      labels:
        app: dataaccessmsauthorizefundstransferbiller-crm
    spec:
      
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          env:
            - name: CORE_MS_EXTERNAL_SERVICE_IP
              value: "coremsexternalservice-crm.teresol.svc.cluster.local"
            - name: CORE_MS_EXTERNAL_SERVICE_PORT
              value: "80"
            - name: DATAACCESS_MS_AUTHORIZEFUNDSTRANSFER_ROOT_PATH
              value: "dataaccessmsauthorizefundstransferbiller-crm.teresol.svc.cluster.local"
            - name: CORE_MS_EXTERNAL_SERVICE_RDTIMEOUT
              value: "66000"
            - name: TRANSACTION_TIMEOUT
              value: "70"

          image: harbor.teresol.com/teresol/dataaccessmsauthorizefundstransferbiller:1.1.1-teller
          imagePullPolicy: Always
          name: dataaccessmsauthorizefundstransferbiller-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

