---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbilldetail-crm
  name: dataaccessmsbilldetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31746
  selector:
    app: dataaccessmsbilldetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbilldetail-crm
  name: dataaccessmsbilldetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbilldetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbilldetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbilldetail:0.0.4-crm
          imagePullPolicy: Always
          name: dataaccessmsbilldetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
