---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol    
  labels:
    app: dataaccessmsbeneficiarydetail-crm
  name: dataaccessmsbeneficiarydetail-crm
spec:
  ports:
    - name: http
      nodePort: 31798
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsbeneficiarydetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbeneficiarydetail-crm
  name: dataaccessmsbeneficiarydetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbeneficiarydetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbeneficiarydetail-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbeneficiarydetail:1.0.2-crm
          imagePullPolicy: Always
          name: dataaccessmsbeneficiarydetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
