---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbiometricdetail-crm
  name: dataaccessmsbiometricdetail-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31602
  selector:
    app: dataaccessmsbiometricdetail-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsbiometricdetail-crm
  name: dataaccessmsbiometricdetail-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsbiometricdetail-crm
  template:
    metadata:
      labels:
        app: dataaccessmsbiometricdetail-crm
    spec:
      containers:
        - name: dataaccessmsbiometricdetail-crm
          env:
           - name: CORE_MS_EXTERNAL_SERVICE_IP
             value: "coremsexternalservice-crm"
           - name: CORE_MS_EXTERNAL_SERVICE_PORT
             value: "80"
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsbiometricdetail:2.1.8-crm
          imagePullPolicy: Always
          name: dataaccessmsbiometricdetail-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
