---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscreatematrix-crm
  name: dataaccessmscreatematrix-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31466
  selector:
    app: dataaccessmscreatematrix-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmscreatematrix-crm
  name: dataaccessmscreatematrix-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmscreatematrix-crm
  template:
    metadata:
      labels:
        app: dataaccessmscreatematrix-crm
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmscreatematrix:1.1.4-crm-fbr
          imagePullPolicy: Always
          name: dataaccessmscreatematrix-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
