---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol     
  labels:
    app: dataaccessmsparamsdetails-crm
  name: dataaccessmsparamsdetails-crm
spec:
  ports:
    - name: http
      nodePort: 31417
      port: 80
      targetPort: 8080
  selector:
    app: dataaccessmsparamsdetails-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: dataaccessmsparamsdetails-crm
  name: dataaccessmsparamsdetails-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessmsparamsdetails-crm
  template:
    metadata:
      labels:
        app: dataaccessmsparamsdetails-crm
    spec:

      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap
          image: harbor.teresol.com/teresol/dataaccessmsparamsdetails:1.1.2-crm
          imagePullPolicy: Always
          name: dataaccessmsparamsdetails-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
