---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coreapireport-crm
  name: coreapireport-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    app: coreapireport-crm
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coreapireport-crm
  name: coreapireport-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapireport-crm
  template:
    metadata:
      labels:
        app: coreapireport-crm
    spec:
      #nodeSelector:
        #kubernetes.io/role: CORE-WORKER
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT

            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_LOG_LEVEL

            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_REPORT

            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_SECRET_REPORT

            - name: CORE_MS_TEMPLATING_ENGINE_WEBCLIENT_IP
              value: "coremstemplatingengine-crm"
            - name: CORE_MS_TEMPLATING_ENGINE_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_REPORT_DETAIL_WEBCLIENT_IP
              value: "dataaccessmsreport-crm"
            - name: DATAACCESS_REPORT_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: EXPRESS_URL
              value: http://coremsreportexpress-crm.reporting.svc.cluster.local:80

            - name: JASPER_URL
              value: "http://coremsreport.teresol.svc.cluster.local:80"

            - name: CORE_MS_REPORT_BIRT_WEBCLIENT_IP
              value: "coremsreportbirt-crm.reporting.svc.cluster.local"
            - name: CORE_MS_REPORT_BIRT_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_UPLOAD_NIFT_WEBCLIENT_IP
              value: "coremsuploadnift-crm.teresol.svc.cluster.local"
            - name: CORE_MS_UPLOAD_NIFT_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_REPORT_BIRT_QUARKUS_WEBCLIENT_IP
              value: "coremsreportbirtquarkus-crm.reporting.svc.cluster.local"
            - name: CORE_MS_REPORT_BIRT_QUARKUS_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_REPORT_BIRT_QUARKUS_POOLING_WEBCLIENT_IP
              value: "coremsreportbirtquarkuspooling-crm.reporting.svc.cluster.local"
            - name: CORE_MS_REPORT_BIRT_QUARKUS_POOLING_WEBCLIENT_PORT
              value: "80"

            - name: CORE_MS_REPORT_BIRT_QUARKUS_POOLING_GET_FILE_WEBCLIENT_IP
              value: "coremsreportbirtquarkuspooling-crm.reporting.svc.cluster.local"
            - name: CORE_MS_REPORT_BIRT_QUARKUS_POOLING_GET_FILE_WEBCLIENT_PORT
              value: "80"

            - name: QUARKUS_POOLING_FILE_GET_TIMEOUT
              value: "60000"

          image: harbor.teresol.com/reporting/coreapireport:0.2.7-crm
          imagePullPolicy: Always
          name: coreapireport-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

