---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app: coremsreportexpress-crm
  name: coremsreportexpress-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coremsreportexpress-crm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coremsreportexpress-crm
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "development"

            - name: LOG_LEVEL
              value: "debug"

            - name: DATAACCESS_COMPANY_DETAIL_WEBCLIENT_IP
              value: "dataaccessmscompanydetail-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_COMPANY_DETAIL_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_IP
              value: "dataaccessmsclearinginstrument-crm.teresol.svc.cluster.local"
            - name: DATAACCESS_CLEARING_INSTRUMENT_WEBCLIENT_PORT
              value: "80"

            - name: DATAACCESS_TIE_UP_REPORTING_WEBCLIENT_IP
              value: "dataaccessmstieupreporting.esm.svc.cluster.local"
            - name: DATAACCESS_TIE_UP_REPORTING_WEBCLIENT_PORT
              value: "80"

          image: harbor.teresol.com/reporting/coremsreportexpress:0.0.4-crm
          name: coremsreportexpress-crm
          ports:
            - containerPort: 8080
      restartPolicy: Always

##############################################
---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app: coremsreportexpress-crm
  name: coremsreportexpress-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: coremsreportexpress-crm
  type: ClusterIP
