---
apiVersion: v1
kind: Service
metadata:
  namespace: reporting
  labels:
    app.kubernetes.io/name: dataaccessmsreport-teller
  name: dataaccessmsreport-teller
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32330
  selector:
    app.kubernetes.io/name: dataaccessmsreport-teller
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reporting
  labels:
    app.kubernetes.io/name: dataaccessmsreport-teller
  name: dataaccessmsreport-teller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataaccessmsreport-teller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dataaccessmsreport-teller
    spec:
      nodeName: r2bcbsint23.bank.alhabib.com            #r2bcbsint29.bank.alhabib.com

      #knodeSelector:
        #kubernetes.io/role: CORE-WORKER
      containers:
        - envFrom:
            - configMapRef:
                name: dataaccess-svc-configmap

          image: harbor.teresol.com/reporting/dataaccessmsreport:3.1.4-teller
          imagePullPolicy: Always
          name: dataaccessmsreport-teller
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /configuration
              name: dataaccessmsreport-data
          securityContext:
             capabilities:
                add: ["SYS_ADMIN"]

      restartPolicy: Always
      volumes:
        - name: dataaccessmsreport-data
          hostPath:
             path: /dataaccessmsreport
             type: DirectoryOrCreate
