---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tlr-rep-rep-uc14-whtdccb2016
  name: tlr-rep-rep-uc14-whtdccb2016
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlr-rep-rep-uc14-whtdccb2016
  template:
    metadata:
      labels:
        app: tlr-rep-rep-uc14-whtdccb2016
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/tlr-rep-rep-uc14-whtdccb2016:1.1.9
          imagePullPolicy: Always
          name: tlr-rep-rep-uc14-whtdccb2016
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tlr-rep-rep-uc14-whtdccb2016
  name: tlr-rep-rep-uc14-whtdccb2016
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: tlr-rep-rep-uc14-whtdccb2016
#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tlr-rep-rep-uc14-whtdccb2016
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/TLR_REP_REP_UC14_WHTDCCB2016`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: tlr-rep-rep-uc14-whtdccb2016
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret

