---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  name: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  template:
    metadata:
      labels:
        app: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc:1.0.28
          imagePullPolicy: Always
          name: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  name: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  type: ClusterIP

#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/TLR_IC_UC7a_CPU_ACT_INST_ACT_C_R_AA_IWC`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: tlr-ic-uc7a-cpu-act-inst-act-c-r-aa-iwc
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret

