---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  name: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  template:
    metadata:
      labels:
        app: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
    spec:
      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn:1.0.5m
          imagePullPolicy: Always
          name: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  name: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  type: ClusterIP

#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/TLR_IC_UC2_CPU_ACT_INST_ACT_SCAN_INST_PN_SCN`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: tlr-ic-uc2-cpu-act-inst-act-scan-inst-pn-scn
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret

