---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tns-mb-uc12-monbatch
  name: tns-mb-uc12-monbatch
  namespace: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tns-mb-uc12-monbatch
  template:
    metadata:
      labels:
        app: tns-mb-uc12-monbatch
    spec:
      #knodeSelector:
        #kubernetes.io/role: FSM-WORKER

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:
        - envFrom:
            - configMapRef:
                name: fsm-configmap
          image: harbor.teresol.com/fsm/tns-mb-uc12-monbatch:1.1.3
          imagePullPolicy: Always
          name: tns-mb-uc12-monbatch
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tns-mb-uc12-monbatch
  name: tns-mb-uc12-monbatch
  namespace: fsm
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: tns-mb-uc12-monbatch
  type: ClusterIP

#################################

#############################################################
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tns-mb-uc12-monbatch
  namespace: fsm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`services.teresol-bahl.com`) && PathPrefix(`/fsm/TNS_MB_UC12_MonBatch`)
      kind: Rule
      middlewares:
        - name: cors-middleware
          namespace: fsm
      services:
        - kind: Service
          name: tns-mb-uc12-monbatch
          namespace: fsm
          port: 3500
  tls:
    secretName: bahl-tls-secret
