---
apiVersion: v1
kind: Service
metadata:
  namespace: teresol
  labels:
    app: coreapimatrix-crm
  name: coreapimatrix-crm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31462
  selector:
    app: coreapimatrix-crm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teresol
  labels:
    app: coreapimatrix-crm
  name: coreapimatrix-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapimatrix-crm
  template:
    metadata:
      labels:
        app: coreapimatrix-crm
    spec:

      hostAliases:
      - ip: "10.90.95.52"
        hostnames:
        - "core.teresol-bahl.com"
      - ip: "10.90.95.53"
        hostnames:
        - "services.teresol-bahl.com"

      containers:

        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: TZ

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_HTTP_PORT



            - name: QUARKUS_TLS_TRUST_ALL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_TLS_TRUST_ALL

            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: QUARKUS_OIDC_AUTH_SERVER_URL

            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: coreapi-svc-configmap
                  key: CLIENT_ID_MATRIX



            - name: CORE_MS_CREATE_MATRIX_IP
              value: "coremsmatrix-crm.teresol.svc.cluster.local"
            - name: CORE_MS_CREATE_MATRIX_PORT
              value: "80"

          image: harbor.teresol.com/teresol/coreapimatrix:0.0.2-crm
          imagePullPolicy: Always
          name: coreapimatrix-crm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

